### ISSUE TITLE
Add YouTubers to the website

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/youtubers-birthdays#1]
Add Youtubers to index.html

You must state their:
- Category (eg: Gaming, Tech)
- Name (YouTube channel name ONLY)
- Birthday
- Total Views as of Jan 2023 (Approx)

NOTE - THE FINAL DECISION ON WHETHER THE YOUTUBER IS ADDED OR NOT, IS UP TO ME. I WILL NOT ADD CONTROVERSIAL YOUTUBERS TO A EXTENT, ETC.

**Comment by Harsh-Daga** [comment]
Hey, 
Can I work on this ?

**Comment by Phil94comp** [comment]
If a youtuber fits in more than one category, do I need to add the youtuber for each category the youtuber qualifies for, or should I list the youtuber only once?

**Comment by KendallDoesCoding** [comment]
> If a youtuber fits in more than one category, do I need to add the youtuber for each category the youtuber qualifies for, or should I list the youtuber only once?

What is the YouTuber, and what is their catergory?

I mean, for eg: they are a Gamer and a Coder, you can say - Gaming, Coding.. But, if they upload more coding then gaming, then say coding solely.

**Comment by anshuman0123** [comment]
Hey can I work on this

**Comment by KendallDoesCoding** [comment]
> Not a specific person is going to be assigned to this issue. It's just a generic one. You just need to add the youtubers to index.html and make a Pull Request.

Not a specific person is going to be assigned to this issue. It's just a generic one. You just need to add the youtubers to index.html and make a Pull Request.

**Comment by vansh2552** [comment]
Hi @KendallDoesCoding . I have added a youtuber and created a PR for the same. Let me know if there are any issues.
Ps: This is my first Open source contribution.

**Comment by KendallDoesCoding** [comment]
Shifted to #66
