### ISSUE TITLE
Separate CSS from HTML 

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/youtubers-birthdays#3]
Move the css (style) into a separate file called `styles.css` and link it back to the HTML by pasting the following into the head:

```
  <link rel="stylesheet" href="styles.css">
```

**Comment by PUJAmangale1221** [comment]
Hey Maintainers, I want to contribute to this issue how can I proceed to do so...?

**Comment by KendallDoesCoding** [comment]
Fixed in 26ba43f.
