### ISSUE TITLE
List "Total Views" from the last month/week (closest date possible) [SOCIALBLADE API]

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/youtubers-birthdays#4]
Using the socialblade API, list "Total Views" as the most recent available (last month, last week, etc).
https://socialblade.com/business-api

**Comment by iONBain** [comment]
Hi @KendallDoesCoding , this is a paid API and we need to search any different api service which fits our requirement.

**Comment by KendallDoesCoding** [comment]
Name of the paid API?

**Comment by KendallDoesCoding** [comment]
> Hi @KendallDoesCoding , this is a paid API and we need to search any different api service which fits our requirement.

Can you help find a API?

**Comment by iONBain** [comment]
Yes @KendallDoesCoding , I found Youtube data API, it requires an api key (which is free, I have created one, you can too!) 
Can we connect somewhere (maybe discord) to discuss the approach ?

**Comment by KendallDoesCoding** [comment]
> Yes @KendallDoesCoding , I found Youtube data API, it requires an api key (which is free, I have created one, you can too!) json received contains details like viewCount, Total video count and subscribers count as well Can we connect somewhere (maybe discord) to discuss the approach ?
> 
> Attachment - ![image](https://user-images.githubusercontent.com/95289741/229261600-b20a9b3a-e63c-4483-bda9-43f1c0ebb8bd.png)

Sure. What's your discord.

Can you work on this Issue?

**Comment by iONBain** [comment]
sure, my dc is bhaskar#6847
I can work on it, first will work on that sort feature :p

**Comment by KendallDoesCoding** [comment]
CHATGPT says we can solve this issue by:

```
How can I use a API to get the total current views of a YouTube channel on my website?
```
To get the total current views of a YouTube channel on your website using API, you can follow these steps:

- Go to the Google Developers Console and create a new project.
- Enable the YouTube Data API for your project.
- Create a new API key for your project.
- Use the API key to make a request to the YouTube Data API to get the channel statistics.
- Parse the response to extract the total view count of the channel.
- Display the total view count on your website.
- Here's an example code snippet in JavaScript that demonstrates how to get the total view count of a YouTube channel using the API:

```
// Replace YOUR_API_KEY with your actual API key
const apiKey = 'YOUR_API_KEY';
const channelId = 'UC_x5XG1OV2P6uZZ5FSM9Ttw'; // Replace with the channel ID you want to get the view count for

// Make a request to the YouTube Data API to get the channel statistics
fetch(`https://www.googleapis.com/youtube/v3/channels?part=statistics&id=${channelId}&key=${apiKey}`)
  .then(response => response.json())
  .then(data => {
    // Parse the response to extract the total view count of the channel
    const viewCount = data.items[0].statistics.viewCount;

    // Display the total view count on your website
    document.getElementById('view-count').textContent = viewCount;
  })
  .catch(error => console.error(error));
```

In this example, we're using the fetch function to make a GET request to the YouTube Data API's channels endpoint with the part parameter set to statistics and the id parameter set to the channel ID we want to get the view count for. We're also passing in our API key as a query parameter.

Once we get the response from the API, we parse it to extract the total view count of the channel from the 
statistics
 object in the response. Finally, we display the view count on our website by setting the text content of an HTML element with the ID 
view-count

**Comment by KendallDoesCoding** [comment]
> sure, my dc is bhaskar#6847 I can work on it, first will work on that sort feature :p

I sent a friend req on discord.

**Comment by MayankBansal12** [comment]
Hey @KendallDoesCoding, is this issue still open?

**Comment by KendallDoesCoding** [comment]
> Hey @KendallDoesCoding, is this issue still open?

Yes. Do you want to be assigned?

**Comment by MayankBansal12** [comment]
Sure. Can we connect on Discord to discuss the issue and approach to solve it? If yes, here is my username: Mayank12#1117

**Comment by vansh2552** [comment]
Hi @KendallDoesCoding , Is anyone working on this issue?

**Comment by MayankBansal12** [comment]
Hey, @vansh2552. I am working on this issue as of now. Please feel free to look out for some other issues.

**Comment by vansh2552** [comment]
@KendallDoesCoding Is there any issue revolving around github actions since I see you have a actions workflow. Or any functionality that you wish to add using actions?

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding Is there any issue revolving around github actions since I see you have a actions workflow. Or any functionality that you wish to add using actions?

Not really, but if you have any ideas, you can go ahead and create a github issue in the repo, and if I approve the issue you can get to work.
