### ISSUE TITLE
To add an array for storing data.

### ISSUE THREAD

**Issue by Ar-Akhil** [KendallDoesCoding/youtubers-birthdays#45]
Suggestion to add array to store the data rather than manual updating it on HTML, its to make data easily accessible for every use case.

**Comment by KendallDoesCoding** [comment]
> Suggestion to add array to store the data rather than manual updating it on HTML, its to make data easily accessible for every use case.

The array will have to be made in JS?

**Comment by matthiasmulzet** [comment]
Hello, can i work on this ?

**Comment by MayankBansal12** [comment]
Opened a PR #54 to add the database

**Comment by KendallDoesCoding** [comment]
@MayankBansal12 had started working on this from a long time since we spoke on Discord.

**Comment by KendallDoesCoding** [comment]
fixed in #54
