### ISSUE TITLE
Display number of total channels on the list.

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/youtubers-birthdays#5]
Using js I think, we can display the number of total channels on the list.
under "Youtubers' Birthdays" above the table, put a text:

```
YouTubers on the list: <amount>
```

**Comment by AshwanthramKL** [comment]
@KendallDoesCoding, Hey can I try my hand at this?

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding, Hey can I try my hand at this?

Sure. Assigned

**Comment by KendallDoesCoding** [comment]
@AshwanthramKL - any update?

**Comment by AshwanthramKL** [comment]
@KendallDoesCoding Will be submitting a PR real soon.

**Comment by KendallDoesCoding** [comment]
Sure. Take your time
