### ISSUE TITLE
[BUG] YouTuber added 2 times

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/youtubers-birthdays#71]
The youtuber was added twice because I may've pressed to add youtuber button twice. But, we have made it so that it cannot add a single youtuber twice.

![image](https://github.com/KendallDoesCoding/youtubers-birthdays/assets/84712013/e12705f9-7c73-4904-843c-0d424bcf8640)

**Comment by KendallDoesCoding** [comment]
Update: when i removed the youtuber it removed only 1.

**Comment by KendallDoesCoding** [comment]
@MayankBansal12 - please check this.

**Comment by MayankBansal12** [comment]
> Update: when i removed the youtuber it removed only 1.

That's because it will fetch first or one entry with that name and delete it.

**Comment by MayankBansal12** [comment]
But this issue will arise in case the server is slow. By clicking the add button twice both requests will be processed simultaneously and since no prior entry with that name exists, it will create two new entries with the same details. To solve this, we should disable the add button once details are submitted.

**Comment by KendallDoesCoding** [comment]
Is that easy to do?

*Thanks,*
*Kendall Does Coding*

*Portfolio
<https://panoprey.com/click?redirect=https%3A%2F%2Fkendalldoescoding.gq&dID=1693501977122&hashId=07132352475772708f4bab9ac742f4cbfbd52641b4e505d34f1dd46db3553b314cdb48&linkName=Portfolio>*
*Github
<https://panoprey.com/click?redirect=https%3A%2F%2Fgithub.com%2FKendallDoesCoding&dID=1693501977122&hashId=07132352475772708f4bab9ac742f4cbfbd52641b4e505d34f1dd46db3553b314cdb48&linkName=Github>*
*Youtube*
<https://panoprey.com/click?redirect=https%3A%2F%2Fkendalldoescoding.gq%2FcodingYT&dID=1693501977122&hashId=07132352475772708f4bab9ac742f4cbfbd52641b4e505d34f1dd46db3553b314cdb48&linkName=Youtube>

**Comment by MayankBansal12** [comment]
Yes. I have added this as good first issue. If no one fixes it, then I will do it soon.

**Comment by KendallDoesCoding** [comment]
> Yes. I have added this as good first issue. If no one fixes it, then I will do it soon.

👍

**Comment by love-sonkar** [comment]
i have fixed #71 this issue in my form validation #77 PR, when user fill all input with proper validation and press the add button, i have set the disabled property to the button to prevent api call twice, it will send only one POST request to save data in database.

**Comment by MayankBansal12** [comment]
Great! I will check the PR and merge the changes.

**Comment by love-sonkar** [comment]
thanks I'm waiting 🙂

**Comment by MayankBansal12** [comment]
PR #77 by @love-sonkar fixes the issue.
