### ISSUE TITLE
[FEAT] Add pagination

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/youtubers-birthdays#8]
Soon*, the list will get quite big. So, I think we should start work on a page number (pagination) system, like was done in:

https://github.com/KendallDoesCoding/mogul-christmas/pull/291
https://github.com/KendallDoesCoding/mogul-christmas/issues/288

**Comment by piyushyadav1617** [comment]
I can make this. So what we need here is a pagination below the list so that the birthdays list can continue to next page and you don't want to scroll the through the list on the single page?

**Comment by KendallDoesCoding** [comment]
> I can make this. So what we need here is a pagination below the list so that the birthdays list can continue to next page and you don't want to scroll through the list on the single page?

Yes. Assigned you.

**Comment by KendallDoesCoding** [comment]
done in #14
