### ISSUE TITLE
[QUESTION] Embed table into README.md

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/youtubers-birthdays#9]
**QUESTION:**
Would it be possible to embed the table from the website to the README.md?

**Comment by Isfaqul** [comment]
Hi there, if you would like to basically have the table embdedded to the read me as a text. I can certainly try and do that. This would be my first open Source contribution. Thansk!

**Comment by KendallDoesCoding** [comment]
@Isfaqul - welcome to open source. I assigned you.

**Comment by Isfaqul** [comment]
Hey, thank you! I have uploaded the solution in my fork. What should I do from here?

**Comment by KendallDoesCoding** [comment]
@Isfaqul go [here](https://github.com/KendallDoesCoding/youtubers-birthdays/compare/master...Isfaqul:youtubers-birthdays:master) and tap - "Create Pull Request", I will then review it, and request changes or merge. If I request changes, you must update the code to what I requested.

**Comment by KendallDoesCoding** [comment]
If you need any help, let me know.

**Comment by KendallDoesCoding** [comment]
@Isfaqul What I wanted is that it automatically updates in README.md when the website is updated. It seems that, that is not possible. I am working on a way where a Github action will automatically take screenshots of the website and upload it to the repo and we link the image to the README.md

**Comment by Isfaqul** [comment]
Ah, I see. I thought we just needed the current set to be added to the readme file. Not a first good issue for me it seems. Maybe, we will need like a python scrapper script, which can do it for us, using selenium or something.

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding Ah, I see. I thought we just needed the current set to be added to the readme file. Not a first good issue for me it seems. Maybe, we will need like a python scrapper script, which can do it for us, using selenium or something.

I thought it could be done via iframe but ig not.

**Comment by KendallDoesCoding** [comment]
That's why I marked it as a good-first-issue.

**Comment by darkcheftar** [comment]
Hey, Is this issue still unsolved?
