### ISSUE TITLE
MortaL not added to README.md

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/youtubers-birthdays#92]
Someone added MortaL to the website, but did not add them to the README.md

Please add them.

**Comment by KendallDoesCoding** [comment]
fixed in #93

**Comment by Ahlyab** [comment]
@KendallDoesCoding please close the issue if it's fixed

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding please close the issue if it's fixed

yes , my bad. i meant to close it before.
