### ISSUE TITLE
Feat : Please provide any button or link to add youtubers

### ISSUE THREAD

**Issue by love-sonkar** [KendallDoesCoding/youtubers-birthdays#94]
In Home Please provide any button or link to add youtubers birthday,
we can't add any youtubers birthday  

if anyone open your home page and wanted to add youtubers,
he/she is confused because thare is no button or link to add youtubers.

![youtube](https://github.com/KendallDoesCoding/youtubers-birthdays/assets/82786865/f07a0cf3-d2bb-494b-be1a-14c207da687c)

**Comment by KendallDoesCoding** [comment]
Good idea!

**Comment by KendallDoesCoding** [comment]
@love-sonkar - The button is only working when the text inside the button is tapped, when the side is tapped it is not working. Can you please fix it?

**Comment by love-sonkar** [comment]
Yes i can fix it

**Comment by KendallDoesCoding** [comment]
> Yes i can fix it

The PR that you made, it messed up the website. Can you please make a new PR to fix this?
